baseURL = 'http://example.org/'
languageCode = 'de'
defaultContentLanguage = "de"
title = 'My New Hugo Site'
theme = 'tss'
relativeURLs = true
removePathAccents = true
disableKinds = ['taxonomy', 'term']